"""Phase 8 Advanced SOC Models

Revision ID: 2a2359406ce7
Revises: 3b2faa5cb851
Create Date: 2026-08-28 19:03:27.012602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a2359406ce7'
down_revision: Union[str, Sequence[str], None] = '3b2faa5cb851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('investigation_id', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('receiver', sa.String(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_agent_messages_investigation_id'), 'agent_messages', ['investigation_id'], unique=False)
    op.create_table('agent_tool_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('investigation_id', sa.String(), nullable=True),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('tool', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tool_policies_investigation_id'), 'agent_tool_policies', ['investigation_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('investigation_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('attack_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id')
    )
    op.create_table('investigation_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('investigation_id', sa.String(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('evidence_quality', sa.String(), nullable=True),
    sa.Column('analyst_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_feedback_investigation_id'), 'investigation_feedback', ['investigation_id'], unique=False)
    op.create_table('investigation_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('investigation_id', sa.String(), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_agent', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['investigation_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_tasks_investigation_id'), 'investigation_tasks', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_tasks_plan_id'), 'investigation_tasks', ['plan_id'], unique=False)
    op.add_column('investigation_plans', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('investigation_plans', sa.Column('depth', sa.String(), nullable=True))
    op.add_column('investigation_plans', sa.Column('status', sa.String(), nullable=True))
    op.add_column('response_actions', sa.Column('description', sa.String(), nullable=True))
    op.add_column('response_actions', sa.Column('risk', sa.Float(), nullable=True))
    op.add_column('response_actions', sa.Column('requested_by', sa.String(), nullable=True))
    op.add_column('response_actions', sa.Column('approved_by', sa.String(), nullable=True))
    op.add_column('response_actions', sa.Column('status', sa.String(), nullable=True))
    op.add_column('response_actions', sa.Column('executed_at', sa.DateTime(), nullable=True))
    op.drop_column('response_actions', 'details')
    op.add_column('triage_results', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('triage_results', sa.Column('reasons', sa.JSON(), nullable=True))
    op.drop_column('triage_results', 'reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('triage_results', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('triage_results', 'reasons')
    op.drop_column('triage_results', 'confidence')
    op.add_column('response_actions', sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('response_actions', 'executed_at')
    op.drop_column('response_actions', 'status')
    op.drop_column('response_actions', 'approved_by')
    op.drop_column('response_actions', 'requested_by')
    op.drop_column('response_actions', 'risk')
    op.drop_column('response_actions', 'description')
    op.drop_column('investigation_plans', 'status')
    op.drop_column('investigation_plans', 'depth')
    op.drop_column('investigation_plans', 'priority')
    op.drop_index(op.f('ix_investigation_tasks_plan_id'), table_name='investigation_tasks')
    op.drop_index(op.f('ix_investigation_tasks_investigation_id'), table_name='investigation_tasks')
    op.drop_table('investigation_tasks')
    op.drop_index(op.f('ix_investigation_feedback_investigation_id'), table_name='investigation_feedback')
    op.drop_table('investigation_feedback')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_agent_tool_policies_investigation_id'), table_name='agent_tool_policies')
    op.drop_table('agent_tool_policies')
    op.drop_index(op.f('ix_agent_messages_investigation_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    # ### end Alembic commands ###
