"""sandbox_session_v2

Revision ID: 3aa3db865eb0
Revises: bf9b39d68642
Create Date: 2026-08-28 18:01:17.571110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa3db865eb0'
down_revision: Union[str, Sequence[str], None] = 'bf9b39d68642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sandbox_sessions', sa.Column('timeout', sa.Float(), nullable=True))
    op.add_column('sandbox_sessions', sa.Column('browser_type', sa.String(), nullable=True))
    op.add_column('sandbox_sessions', sa.Column('error', sa.String(), nullable=True))
    op.add_column('sandbox_sessions', sa.Column('artifact_count', sa.Integer(), nullable=True))
    op.add_column('sandbox_sessions', sa.Column('event_count', sa.Integer(), nullable=True))
    from sqlalchemy.dialects import postgresql
    sandboxstatus = postgresql.ENUM('QUEUED', 'STARTING', 'RUNNING', 'COMPLETED', 'TIMEOUT', 'FAILED', 'TERMINATED', name='sandboxstatus')
    sandboxstatus.create(op.get_bind())
    
    op.alter_column('sandbox_sessions', 'status',
               existing_type=sa.VARCHAR(),
               type_=sandboxstatus,
               postgresql_using="status::sandboxstatus",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sandbox_sessions', 'status',
               existing_type=sa.Enum('QUEUED', 'STARTING', 'RUNNING', 'COMPLETED', 'TIMEOUT', 'FAILED', 'TERMINATED', name='sandboxstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('sandbox_sessions', 'event_count')
    op.drop_column('sandbox_sessions', 'artifact_count')
    op.drop_column('sandbox_sessions', 'error')
    op.drop_column('sandbox_sessions', 'browser_type')
    op.drop_column('sandbox_sessions', 'timeout')
    # ### end Alembic commands ###
