"""Update AgentRun for Phase 3

Revision ID: bf9b39d68642
Revises: f09d3455e20b
Create Date: 2026-08-28 17:49:32.491254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf9b39d68642'
down_revision: Union[str, Sequence[str], None] = 'f09d3455e20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('agent_version', sa.String(), nullable=True))
    op.add_column('agent_runs', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('agent_runs', sa.Column('input_summary', sa.String(), nullable=True))
    op.add_column('agent_runs', sa.Column('output_summary', sa.String(), nullable=True))
    op.add_column('agent_runs', sa.Column('retry_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'retry_count')
    op.drop_column('agent_runs', 'output_summary')
    op.drop_column('agent_runs', 'input_summary')
    op.drop_column('agent_runs', 'duration')
    op.drop_column('agent_runs', 'agent_version')
    # ### end Alembic commands ###
