"""add_graph_journey_models

Revision ID: c69ff9264885
Revises: a99f7ce59c46
Create Date: 2026-08-28 18:28:15.456640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69ff9264885'
down_revision: Union[str, Sequence[str], None] = 'a99f7ce59c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_journey_steps',
    sa.Column('investigation_id', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('risk_before', sa.Float(), nullable=True),
    sa.Column('risk_after', sa.Float(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_nodes',
    sa.Column('investigation_id', sa.String(), nullable=True),
    sa.Column('node_type', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('value_hash', sa.String(), nullable=True),
    sa.Column('safe_display_value', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessments',
    sa.Column('investigation_id', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('triggered_by', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_edges',
    sa.Column('investigation_id', sa.String(), nullable=True),
    sa.Column('source_node_id', sa.String(), nullable=True),
    sa.Column('target_node_id', sa.String(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['evidence_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['evidence_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_edges')
    op.drop_table('risk_assessments')
    op.drop_table('evidence_nodes')
    op.drop_table('attack_journey_steps')
    # ### end Alembic commands ###
