"""Add InvestigationEvent and Finding models

Revision ID: f09d3455e20b
Revises: 
Create Date: 2026-08-28 17:31:13.396564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f09d3455e20b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigations', sa.Column('normalized_input', sa.String(), nullable=True))
    op.add_column('investigations', sa.Column('current_stage', sa.String(), nullable=True))
    op.add_column('investigations', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigations', 'completed_at')
    op.drop_column('investigations', 'current_stage')
    op.drop_column('investigations', 'normalized_input')
    # ### end Alembic commands ###
